services:
  - type: web
    name: restaurant-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash scripts/start_render.sh
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: BABEL_DEFAULT_LOCALE
        value: ar
      - key: USE_EVENTLET
        value: "0"

databases:
  - name: restaurant-db
    databaseName: restaurant_system
    user: restaurant_user
