services:
  - type: web
    name: restaurant-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_gunicorn.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: BABEL_DEFAULT_LOCALE
        value: ar

databases:
  - name: restaurant-db
    databaseName: restaurant_system
    user: restaurant_user
